export const INIT_BLOG = 'INIT_BLOG'
export const INIT_BLOG_SUCCEED = 'INIT_BLOG_SUCCESS'
export const INIT_BLOG_FAILED = 'INIT_BLOG_FAILED'

export const NEW_BLOG = 'NEW_BLOG'
export const NEW_BLOG_SUCCEED = 'NEW_BLOG_SUCCEED'
export const NEW_BLOG_FAILED = 'NEW_BLOG_FAILED'

export const LIKE_BLOG = 'LIKE_POST'
export const LIKE_BLOG_SUCCEED = 'LIKE_BLOG_SUCCEED'
export const LIKE_BLOG_FAILED = 'LIKE_BLOG_FAILED'

export const DELETE_BLOG = 'DELETE_BLOG'
export const DELETE_BLOG_SUCCEED = 'DELETE_BLOG_SUCCEED'
export const DELETE_BLOG_FAILED = 'DELETE_BLOG_FAILED'

export const ADD_COMMENT = 'ADD_COMMENT'
export const ADD_COMMENT_SUCCEED = 'ADD_COMMENT_SUCCEED'
export const ADD_COMMENT_FAILED = 'ADD_COMMENT_FAILED'